# Generated by Django 4.2.20 on 2025-03-27 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service_manager', '0002_service_oil_filter_changed_service_oil_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='oil_quantity',
        ),
        migrations.RemoveField(
            model_name='service',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='owner_phone',
        ),
        migrations.RemoveField(
            model_name='service',
            name='plate_number',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='service',
            name='brake_fluid_checked',
            field=models.BooleanField(default=False, verbose_name='روغن ترمز چک شد'),
        ),
        migrations.AddField(
            model_name='service',
            name='gearbox_oil_change_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تعویض واسکازین'),
        ),
        migrations.AddField(
            model_name='service',
            name='gearbox_oil_checked',
            field=models.BooleanField(default=False, verbose_name='واسکازین چک شد'),
        ),
        migrations.AddField(
            model_name='service',
            name='power_steering_fluid_checked',
            field=models.BooleanField(default=False, verbose_name='روغن هیدرولیک فرمان چک شد'),
        ),
        migrations.AddField(
            model_name='service',
            name='radiator_water_checked',
            field=models.BooleanField(default=False, verbose_name='چک آب رادیاتور انجام شد'),
        ),
        migrations.AddField(
            model_name='service',
            name='windshield_washer_filled',
            field=models.BooleanField(default=False, verbose_name='شیشه شور عقب و جلو پر شد'),
        ),
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='service',
            name='mechanic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='mileage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='next_service_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='oil_type',
            field=models.CharField(max_length=100),
        ),
    ]
