# Generated by Django 4.2.20 on 2025-03-27 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_manager', '0006_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='current_mileage',
        ),
        migrations.AlterField(
            model_name='car',
            name='plate_number',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='شماره پلاک باید به فرمت 59-365م33 باشد', regex='^\\d{2}-\\d{3}[مع]\\d{2}$')]),
        ),
    ]
